version: "3.7"

services:

  db:
    container_name: db
    image: "postgres:13-alpine"
    environment:
      - POSTGRES_DATABASES=${POSTGRES_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    networks:
      my_api_network:


  django_app:
    volumes:
      - media_volume:/usr/src/app/media
    container_name: django_app
    build: ./
    command: sh -c "python manage.py collectstatic --noinpu && python manage.py migrate && uvicorn assemblers_workplace.asgi:application --host 0.0.0.0 --port ${API_PORT}"
      - ./:/usr/src/app/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      my_api_network:


networks:
  my_api_network:
    driver: bridge