version: "3.7"

services:

  db:
    container_name: db
    image: "postgres:13-alpine"
    environment:
      - POSTGRES_DATABASES=${POSTGRES_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - '5432:5432'
    networks:
      my_api_network:


networks:
  my_api_network:
    driver: bridge