# Generated by Django 4.2.5 on 2023-09-28 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_wbordermodel_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wbordermodel",
            name="business_account",
        ),
        migrations.RemoveField(
            model_name="wbordermodel",
            name="task",
        ),
        migrations.RemoveField(
            model_name="wbordermodel",
            name="warehouse",
        ),
        migrations.AddField(
            model_name="wbsupplymodel",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.taskmodel",
            ),
        ),
    ]
