# Generated by Django 4.2.5 on 2023-09-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_remove_wbordermodel_business_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wbordermodel",
            name="order_products",
            field=models.ManyToManyField(
                blank=True, related_name="orders", to="app.wborderproductmodel"
            ),
        ),
        migrations.AlterField(
            model_name="wbordermodel",
            name="wb_supply_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
