# Generated by Django 4.2.5 on 2023-10-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_wbordermodel_order_products_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskmodel",
            name="completed",
        ),
        migrations.RemoveField(
            model_name="wborderproductmodel",
            name="nm_id",
        ),
        migrations.AddField(
            model_name="taskmodel",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="taskmodel",
            name="task_state",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("CREATE_SUPPLY", "Create Supply"),
                    ("ADD_ORDERS", "Add Orders"),
                    ("GET_ORDERS_STICKERS", "Get Orders Stickers"),
                    ("SEND_SUPPLY_TO_DELIVER", "Send Supply To Deliver"),
                    ("GET_SUPPLY_STICKER", "Get Supply Sticker"),
                    ("CLOSE", "Close"),
                ],
                default="NEW",
                max_length=32,
            ),
        ),
    ]
