# Generated by Django 4.2.5 on 2023-10-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_remove_taskmodel_completed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskmodel",
            name="amount",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="task_state",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("CREATE_SUPPLY", "Create Supply"),
                    ("ADD_ORDERS", "Add Orders"),
                    ("GET_ORDERS_STICKERS", "Get Orders Stickers"),
                    ("SEND_SUPPLY_TO_DELIVER", "Send Supply To Deliver"),
                    ("GET_SUPPLY_STICKER", "Get Supply Sticker"),
                    ("CLOSE", "Close"),
                ],
                default="NEW",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="wbordermodel",
            name="wb_address",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="wbordermodel",
            name="wb_offices",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="wbordermodel",
            name="wb_skus",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="wbordermodel",
            name="wb_user",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
