# Generated by Django 4.2.5 on 2023-10-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_taskmodel_stickers_document_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taskmodel",
            old_name="stickers_document",
            new_name="stickers_pdf_doc",
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="task_state",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("CREATE_SUPPLY", "Create Supply"),
                    ("ADD_ORDERS", "Add Orders"),
                    ("GET_ORDERS_STICKERS", "Get Orders Stickers"),
                    ("SEND_SUPPLY_TO_DELIVER", "Send Supply To Deliver"),
                    ("GET_SUPPLY_STICKER", "Get Supply Sticker"),
                    ("CLOSE", "Close"),
                ],
                default="NEW",
                max_length=32,
            ),
        ),
    ]
