# Generated by Django 4.2.5 on 2023-10-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0016_remove_wborderproductmodel_packaging_class_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskmodel",
            name="document",
            field=models.FileField(
                blank=True, null=True, upload_to="files/assemblers_doc"
            ),
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="task_state",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("CREATE_SUPPLY", "Create Supply"),
                    ("ADD_ORDERS", "Add Orders"),
                    ("GET_ORDERS_STICKERS", "Get Orders Stickers"),
                    ("SEND_SUPPLY_TO_DELIVER", "Send Supply To Deliver"),
                    ("GET_SUPPLY_STICKER", "Get Supply Sticker"),
                    ("CLOSE", "Close"),
                ],
                default="NEW",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="wb_order_qr_document",
            field=models.FileField(blank=True, null=True, upload_to="files/orders_qr"),
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="wb_order_stickers_pdf_doc",
            field=models.FileField(blank=True, null=True, upload_to="files/barcodes"),
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="wb_supply_qr_document",
            field=models.FileField(blank=True, null=True, upload_to="files/supply_qr"),
        ),
        migrations.AlterField(
            model_name="wbordermodel",
            name="partA",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="wbordermodel",
            name="partB",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
