# Generated by Django 4.2.5 on 2023-10-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0017_alter_taskmodel_document_alter_taskmodel_task_state_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taskmodel",
            old_name="document",
            new_name="assembler_document",
        ),
        migrations.RenameField(
            model_name="taskmodel",
            old_name="wb_order_stickers_pdf_doc",
            new_name="wb_order_stickers_document",
        ),
        migrations.AddField(
            model_name="taskmodel",
            name="package_document",
            field=models.FileField(
                blank=True, null=True, upload_to="files/package_doc"
            ),
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="task_state",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("CREATE_SUPPLY", "Create Supply"),
                    ("ADD_ORDERS", "Add Orders"),
                    ("GET_ORDERS_STICKERS", "Get Orders Stickers"),
                    ("SEND_SUPPLY_TO_DELIVER", "Send Supply To Deliver"),
                    ("GET_SUPPLY_STICKER", "Get Supply Sticker"),
                    ("CLOSE", "Close"),
                ],
                default="NEW",
                max_length=32,
            ),
        ),
    ]