# Generated by Django 4.2.5 on 2023-11-01 10:50

from django.db import migrations, models
import django.db.models.deletion

from assemblers_workplace.settings import settings


def create_allowed_ips(apps, scschema_editorhe):
    AllowedIpModel = apps.get_model("app", "AllowedIpModel")

    for elem in settings.allowed_ips:
        AllowedIpModel.objects.create(name=elem.name, ip=elem.ip)

class Migration(migrations.Migration):
    dependencies = [
        ("app", "0018_rename_document_taskmodel_assembler_document_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllowedIpModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_created=True, auto_now_add=True),
                ),
                ("name", models.CharField(max_length=256)),
                ("ip", models.CharField(max_length=256)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "allowed_ips",
            },
        ),
        migrations.AlterModelOptions(
            name="taskmodel",
            options={
                "verbose_name": "Сборочное задание",
                "verbose_name_plural": "Сборочные задания",
            },
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="amount",
            field=models.PositiveIntegerField(default=1, verbose_name="Количество"),
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="assembler_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="files/assemblers_doc",
                verbose_name="Сборочный лист",
            ),
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="business_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app.wbbusinessaccountmodel",
                verbose_name="Аккаунт",
            ),
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app.employeemodel",
                verbose_name="Сотрудник",
            ),
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активно"),
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="package_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="files/package_doc",
                verbose_name="Упаковочный лист",
            ),
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="task_state",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("CREATE_SUPPLY", "Create Supply"),
                    ("ADD_ORDERS", "Add Orders"),
                    ("GET_ORDERS_STICKERS", "Get Orders Stickers"),
                    ("SEND_SUPPLY_TO_DELIVER", "Send Supply To Deliver"),
                    ("GET_SUPPLY_STICKER", "Get Supply Sticker"),
                    ("CLOSE", "Close"),
                ],
                default="NEW",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app.wbwarehousemodel",
                verbose_name="Склад",
            ),
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="wb_order_qr_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="files/orders_qr",
                verbose_name="Лист WB qr-кодов",
            ),
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="wb_order_stickers_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="files/barcodes",
                verbose_name="Лист WB штрихкодов",
            ),
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="wb_supply_qr_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="files/supply_qr",
                verbose_name="Qr-код поставки",
            ),
        ),
        migrations.RunPython(create_allowed_ips),
    ]
