# Generated by Django 4.2.5 on 2023-12-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0020_remove_wbordermodel_wb_is_large_cargo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FailedNmIdProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nm_id", models.CharField(unique=True, verbose_name=255)),
                ("name", models.TextField(blank=True, null=True)),
                ("wb_order_id", models.CharField(verbose_name=255)),
                ("fixed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Продукт с проблемным nm_id",
                "verbose_name_plural": "Продукты с проблемными nm_id",
                "db_table": "failed_nm_id_products",
            },
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="task_state",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("CREATE_SUPPLY", "Create Supply"),
                    ("ADD_ORDERS", "Add Orders"),
                    ("GET_ORDERS_STICKERS", "Get Orders Stickers"),
                    ("SEND_SUPPLY_TO_DELIVER", "Send Supply To Deliver"),
                    ("GET_SUPPLY_STICKER", "Get Supply Sticker"),
                    ("CLOSE", "Close"),
                ],
                default="NEW",
                max_length=32,
            ),
        ),
    ]
