# Generated by Django 4.2.5 on 2024-02-16 09:11
import django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0022_wbaccountwarehousemodel_processing_flag_and_more"),
    ]

    operations = [
        migrations.RenameModel('WbAccountWarehouseModel', 'AccountWarehouseModel'),
        migrations.RenameModel('WbBusinessAccountModel', 'BusinessAccountModel'),
        migrations.RenameModel('WbWarehouseModel', 'WarehouseModel'),
        migrations.AlterModelTable(
            name='AccountWarehouseModel',
            table='account_warehouses',
        ),
        migrations.AlterModelTable(
            name='BusinessAccountModel',
            table='business_accounts',
        ),
        migrations.AlterModelTable(
            name='WarehouseModel',
            table='warehouses',
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="business_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app.businessaccountmodel",
                verbose_name="Аккаунт",
            ),
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app.warehousemodel",
                verbose_name="Склад",
            ),
        ),
    ]
