# Generated by Django 4.2.5 on 2024-02-16 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0023_auto_20240216_0911"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountwarehousemodel",
            name="ozon_id",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="businessaccountmodel",
            name="ozon_api_token",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="businessaccountmodel",
            name="ozon_client_id",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="accountwarehousemodel",
            name="business_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_warehouses",
                to="app.businessaccountmodel",
            ),
        ),
        migrations.AlterField(
            model_name="accountwarehousemodel",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_warehouses",
                to="app.warehousemodel",
            ),
        ),
        migrations.AlterField(
            model_name="accountwarehousemodel",
            name="wb_id",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="businessaccountmodel",
            name="wb_token",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="task_state",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("CREATE_SUPPLY", "Create Supply"),
                    ("ADD_ORDERS", "Add Orders"),
                    ("GET_ORDERS_STICKERS", "Get Orders Stickers"),
                    ("SEND_SUPPLY_TO_DELIVER", "Send Supply To Deliver"),
                    ("GET_SUPPLY_STICKER", "Get Supply Sticker"),
                    ("CLOSE", "Close"),
                ],
                default="NEW",
                max_length=32,
            ),
        ),
    ]
