# Generated by Django 4.2.5 on 2024-02-22 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0025_wbtaskmodel_alter_wbsupplymodel_task_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wbordermodel",
            name="order_products",
        ),
        migrations.RemoveField(
            model_name="wbsupplymodel",
            name="wb_orders",
        ),
        migrations.AlterField(
            model_name="wborderproductmodel",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_products",
                to="app.wbordermodel",
            ),
        ),
        migrations.AlterField(
            model_name="wbtaskmodel",
            name="task_state",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("CREATE_SUPPLY", "Create Supply"),
                    ("ADD_ORDERS", "Add Orders"),
                    ("GET_ORDERS_STICKERS", "Get Orders Stickers"),
                    ("SEND_SUPPLY_TO_DELIVER", "Send Supply To Deliver"),
                    ("GET_SUPPLY_STICKER", "Get Supply Sticker"),
                    ("CLOSE", "Close"),
                ],
                default="NEW",
                max_length=32,
            ),
        ),
    ]
